src/engine/DrawManager.java

Add draw method for difficulty screen to DrawManager.java

[SI1-54]ADD: Add draw method for difficulty screen to DrawManager.java

---

.idea/sonarlint/issuestore/index.pb
src/screen/DifficultyScreen.java

[SI1-55]ADD: Add DifficultyScreen.java

---

src/engine/DrawManager.java

Add drawDiffcultyTitle & drawDifficultyOption to DrawManager.java

[SIP-21]UPDATE: Update DrawManager.java for difficulty screen

---

Space-Invaders.iml
src/screen/DifficultyScreen.java

Add DifficultyScreen.java to Screen package

[SIP-22]ADD: Add DifficultyScreen.java

---

.github/workflows/sonar.yml
Space-Invaders.iml
src/engine/Core.java
src/engine/GameState.java
src/entity/EnemyShip.java
src/entity/Entity.java
src/screen/DifficultyScreen.java
src/screen/GameScreen.java
src/screen/ScoreScreen.java

- SIP-23 :  Add difficulty screen case to Core.main
Update game level to make it easier. It was too difficult on normal and hard option.
- SIP-24 :  Add HP function according to difficulty. HP of Enemy Ship is displayed through color.
HP 2 = yellow, 3 = red color.
Modify Color of EnemySpecialShip RED to MAGENTA.
- SIP-25 :  Modify accuracy.  EnemyShipDestroyed/bulletShot(before) -> bulletHitCnt/bulletShot(after)
- FIX : Fix the issue that SPACE KEY did not work when selecting difficulty. Input key setting ENTER -> SPACE when choose difficulty option in …

Difficulty function

---

.github/workflows/sonar.yml
Space-Invaders.iml
src/engine/Core.java
src/engine/DrawManager.java
src/engine/GameState.java
src/entity/EnemyShip.java
src/entity/Entity.java
src/screen/DifficultyScreen.java
src/screen/GameScreen.java
src/screen/ScoreScreen.java

Sip 14 sprint

---

src/engine/DrawManager.java

Draw methods for pause menu. - drawPauseTitle(), drawPauseMenu()

[SIP-26]UPDATE: Add pause draw methods

---

src/screen/GameScreen.java

Add pause methods to GameScreen. Press the ESC key to enter the pause state. 
'How To Play' & 'EXIT' options in pause menu aren't working yet - will be added.

[SIP-29]UPDATE: Add pause methods to GameScreen.java

---

src/engine/Core.java
src/engine/GameState.java
src/screen/GameScreen.java

Add exit function 
- Select 'EXIT' option in pause state to stop the game and exit to title screen. 

[SIP-31]UPDATE: Add Exit function

---

src/engine/Core.java
src/engine/DrawManager.java
src/engine/GameState.java
src/screen/DifficultyScreen.java
src/screen/GameScreen.java
src/screen/HighScoreScreen.java
src/screen/TitleScreen.java

Pause function including exit game function.

Sip 16 sprint

---

src/engine/DrawManager.java

Add draw methods for manual screen 
: drawHowToPlayTitle(), drawHowToPlayMenu(), drawRightCenteredRegularString(), drawLeftCenteredRegularString()

[SIP-27]UPDATE: Add draw methods for manual screen

---

src/screen/HowToPlayScreen.java

[SIP-32]ADD: Add HowToPlayScreen.java to screen package

---

src/engine/Core.java
src/engine/DrawManager.java
src/screen/TitleScreen.java

Add how to play case to Core.main
Modify title draw methods and title menu select methods to add how to play option.

[SIP-33]UPDATE: Add manual option in title screen

---

src/engine/Core.java
src/engine/DrawManager.java
src/screen/GameScreen.java
src/screen/HowToPlayScreen.java
src/screen/TitleScreen.java
src/screen/TutorialScreen.java

Sip 17 sprint

---

src/engine/Audio.java

Add Audio class to manage sounds

[SIP-35]ADD: Add Audio.java to engine package

---

src/screen/TitleScreen.java

[SIP-36]UPDATE: Add BGM to TitleScreen

---

src/engine/DrawManager.java

Add boss stage case to drawCountDown()

[SIP-42]UPDATE: Add draw method for boss stage

---

src/entity/EnemyShip.java
src/entity/EnemyShipFormation.java

[SIP-43]UPDATE: Add boss ship to enemy types

---

src/engine/Core.java
src/screen/GameScreen.java

Add boss stage
Adjust game level

[SIP-44]UPDATE: Add boss stage

---

src/engine/Core.java
src/engine/DrawManager.java
src/entity/EnemyShip.java
src/entity/EnemyShipFormation.java
src/screen/GameScreen.java

Sip 15 sprint
